name: my_project
description: A sample Dart project
version: 1.0.0

# Specify the Dart SDK version constraints
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Add your project dependencies here
  dio: ^5.4.0

dev_dependencies:
  # Add your development dependencies here
  test: ^1.0.0

# Define any additional metadata for your package
# ...
